macos:
  tags:
    - macos10.15
    - cmake
    - conan
  script:
    - echo $BUILD_FOLDER
    - mkdir -p $BUILD_FOLDER
    - pwd
    - ls -lah
    - cd $BUILD_FOLDER
    - cmake -DCMAKE_BUILD_TYPE=Release .. # Specify release for Conan
    - cmake --build . --config Release
  artifacts:
    name: "$BUILD_FOLDER"
    paths:
      - $BUILD_FOLDER/JuceBootstrapGui_artefacts/Release
      - $BUILD_FOLDER/JuceBootstrapPlugin_artefacts/Release

windows:
  tags:
    - win10-x64
    - cmake
    - conan
  script:
    - mkdir -p $BUILD_FOLDER
    - cd $BUILD_FOLDER
    - cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release .. # Specify release for Conan
    - cmake --build . --config Release
  artifacts:
    name: "$BUILD_FOLDER"
    paths:
      - $BUILD_FOLDER/JuceBootstrapGui_artefacts/Release
      - $BUILD_FOLDER/JuceBootstrapPlugin_artefacts/Release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_FOLDER: "juce-bootstrap-$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA-release"
